### ISSUE TITLE
Documentation: Adding the Youtube videos

### ISSUE THREAD

**Issue by AssetBurned** [nielsonm236/NetMod-ServerApp#129]
Hi

Given that you have made some youtube videos about this module and repo, wouldn't it be a good idea to call those videos out in the readme?

CU Assetburned

**Comment by nielsonm236** [comment]
Well, I do have the link in the Wiki ... but I suppose I can add a note in the Readme that says "Look for a link to the YouTube video in the Wiki". That would serve a double purpose: Get people to look at the Wiki, AND get them to see the link to the YouTube videos.
So, good idea.
Mike

**Comment by nielsonm236** [comment]
Addressed in release 20221217 1925.
