### ISSUE TITLE
"Please enter requested format" message does not scroll with browser page in Firefox

### ISSUE THREAD

**Issue by nielsonm236** [nielsonm236/NetMod-ServerApp#31]
Try this: Using Firefox delete the last character of your MAC address, then click Save. A "Please enter requested format" message appears. Now scroll the page up an down. The "Please enter requested format" popup does not stay attached to the MAC field.

If you do this same thing in Chrome the "Please enter requested format" popup stays attached to the MAC field.

I didn't try other browsers.

**Comment by yozik04** [comment]
This is the browser bug

**Comment by nielsonm236** [comment]
There are two browser bugs. Issue #28 (blank fields hose things up), and #31 (this one).

**Comment by yozik04** [comment]
I mean I can not fix it in javascript or HTML.

**Comment by nielsonm236** [comment]
OK - Thanks. This is not critical, and only seems to appear in Firefox.
