### ISSUE TITLE
/98 /99 command does not return the correct size for the page in the HTML header

### ISSUE THREAD

**Issue by nielsonm236** [nielsonm236/NetMod-ServerApp#83]
The title explains the issue. This is fixed and will be in the next release.

**Comment by yozik04** [comment]
I am thinking if it would be easier to use chunked transfer encoding for html delivery See https://greenbytes.de/tech/webdav/rfc2616.html#transfer.codings

Jevgeni

**Comment by nielsonm236** [comment]
Perhaps if I had started out that way :-)
For now I have fixed the rather simple math error for this specific case, and will add "chunked" to my think-about-it list. While pre-calculation of the total length of the transfer is a bit messy, once the code exists it is possibly even a bigger mess to back it out. There are days I feel like I'm working in a maze.

**Comment by yozik04** [comment]
You do not need to precalculate anything. You will replace couple first bytes after your chunk is ready.

Jevgeni

**Comment by nielsonm236** [comment]
Fixed in release 20210821 1541
